# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLine = QtWidgets.QLineEdit(self.centralwidget)
        self.titleLine.setGeometry(QtCore.QRect(30, 70, 113, 22))
        self.titleLine.setObjectName("titleLine")
        self.contentText = QtWidgets.QTextEdit(self.centralwidget)
        self.contentText.setGeometry(QtCore.QRect(30, 100, 104, 87))
        self.contentText.setObjectName("contentText")
        self.authorLine = QtWidgets.QLineEdit(self.centralwidget)
        self.authorLine.setGeometry(QtCore.QRect(30, 200, 113, 22))
        self.authorLine.setObjectName("authorLine")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(30, 250, 93, 28))
        self.saveButton.setObjectName("saveButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.saveButton.clicked.connect(self.saveNote)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))


    def saveNote(self):
        nowTime = datetime.datetime.now().strftime("%H-%M")
        nowDate = datetime.datetime.now().strftime("%Y-%m-%d")
        with open(f"{nowTime}{nowDate}.txt", "w", encoding="utf-8") as f:
            f.write(f"{self.titleLine.text()}\n {self.contentText.toPlainText()}\n -{self.authorLine.text()}")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
