# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.profileGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.profileGroupBox.setGeometry(QtCore.QRect(30, 30, 291, 511))
        self.profileGroupBox.setObjectName("profileGroupBox")
        self.nameGroupBox = QtWidgets.QGroupBox(self.profileGroupBox)
        self.nameGroupBox.setGeometry(QtCore.QRect(-1, 20, 291, 51))
        self.nameGroupBox.setObjectName("nameGroupBox")
        self.nameLine = QtWidgets.QLineEdit(self.nameGroupBox)
        self.nameLine.setGeometry(QtCore.QRect(10, 20, 261, 22))
        self.nameLine.setObjectName("nameLine")
        self.surnameGroupBox = QtWidgets.QGroupBox(self.profileGroupBox)
        self.surnameGroupBox.setGeometry(QtCore.QRect(-1, 80, 291, 61))
        self.surnameGroupBox.setObjectName("surnameGroupBox")
        self.surnameLine = QtWidgets.QLineEdit(self.surnameGroupBox)
        self.surnameLine.setGeometry(QtCore.QRect(10, 30, 261, 22))
        self.surnameLine.setObjectName("surnameLine")
        self.patroCheckBox = QtWidgets.QGroupBox(self.profileGroupBox)
        self.patroCheckBox.setGeometry(QtCore.QRect(0, 150, 291, 61))
        self.patroCheckBox.setObjectName("patroCheckBox")
        self.checkBox = QtWidgets.QCheckBox(self.patroCheckBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.patroLine = QtWidgets.QLineEdit(self.patroCheckBox)
        self.patroLine.setGeometry(QtCore.QRect(150, 20, 121, 22))
        self.patroLine.setObjectName("patroLine")
        self.ageGroupBox = QtWidgets.QGroupBox(self.profileGroupBox)
        self.ageGroupBox.setGeometry(QtCore.QRect(0, 220, 291, 51))
        self.ageGroupBox.setObjectName("ageGroupBox")
        self.ageLine = QtWidgets.QLineEdit(self.ageGroupBox)
        self.ageLine.setGeometry(QtCore.QRect(10, 20, 261, 22))
        self.ageLine.setObjectName("ageLine")
        self.genderGroupBox = QtWidgets.QGroupBox(self.profileGroupBox)
        self.genderGroupBox.setGeometry(QtCore.QRect(0, 270, 291, 131))
        self.genderGroupBox.setObjectName("genderGroupBox")
        self.maleButton = QtWidgets.QRadioButton(self.genderGroupBox)
        self.maleButton.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.maleButton.setObjectName("maleButton")
        self.femaleButton = QtWidgets.QRadioButton(self.genderGroupBox)
        self.femaleButton.setGeometry(QtCore.QRect(10, 50, 95, 20))
        self.femaleButton.setObjectName("femaleButton")
        self.secretButton = QtWidgets.QRadioButton(self.genderGroupBox)
        self.secretButton.setGeometry(QtCore.QRect(10, 80, 95, 20))
        self.secretButton.setObjectName("secretButton")
        self.occupGroupBox = QtWidgets.QGroupBox(self.profileGroupBox)
        self.occupGroupBox.setGeometry(QtCore.QRect(0, 410, 291, 61))
        self.occupGroupBox.setObjectName("occupGroupBox")
        self.occupLine = QtWidgets.QLineEdit(self.occupGroupBox)
        self.occupLine.setGeometry(QtCore.QRect(12, 20, 261, 22))
        self.occupLine.setObjectName("occupLine")
        self.okButton = QtWidgets.QPushButton(self.profileGroupBox)
        self.okButton.setGeometry(QtCore.QRect(10, 480, 261, 28))
        self.okButton.setObjectName("okButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.profileGroupBox.setTitle(_translate("MainWindow", "Profile Creation"))
        self.nameGroupBox.setTitle(_translate("MainWindow", "Name"))
        self.surnameGroupBox.setTitle(_translate("MainWindow", "Surname"))
        self.patroCheckBox.setTitle(_translate("MainWindow", "Patronymics"))
        self.checkBox.setText(_translate("MainWindow", "Has Patronymics"))
        self.ageGroupBox.setTitle(_translate("MainWindow", "Age"))
        self.genderGroupBox.setTitle(_translate("MainWindow", "Gender"))
        self.maleButton.setText(_translate("MainWindow", "Male"))
        self.femaleButton.setText(_translate("MainWindow", "Female"))
        self.secretButton.setText(_translate("MainWindow", "Secret"))
        self.occupGroupBox.setTitle(_translate("MainWindow", "Occupation"))
        self.okButton.setText(_translate("MainWindow", "OK"))

        self.okButton.clicked.connect(self.save)


    def save(self):
        self.data = {}
        self.data["name"] = self.nameLine.text()
        self.data["surname"] = self.surnameLine.text()
        if self.checkBox.isChecked() == True:
            self.data["patronymics"] = self.patroLine.text()
        self.data["age"] = self.ageLine.text()
        if self.maleButton.isChecked() == True:
            self.data["gender"] = self.maleButton.text()
        elif self.femaleButton.isChecked() == True:
            self.data["gender"] = self.femaleButton.text()
        elif self.secretButton.isChecked() == True:
            self.data["gender"] = self.secretButton.text()
        self.data["occupation"] = self.occupLine.text()
        with open("data.json", "w") as file:
            json.dump(self.data, file, ensure_ascii=False, indent=4)






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
